using LupiraTasksApi.Core.Domain.Items;
using Xunit;

namespace LupiraTasksApi.UnitTests;

/// <summary>
/// Order-key arithmetic. The vectors are generated by the <c>fractional-indexing</c> npm package the
/// app clients call, so they pin wire compatibility: a key minted here is a key a phone would mint,
/// and either side can insert between the other's keys. The append test is the regression guard for
/// the old "concatenate a digit per insert" scheme, which grew one character per item.
/// </summary>
public class FractionalIndexTests
{
    [Theory]
    // a, b, expected — from `generateKeyBetween(a, b)` in fractional-indexing.
    [InlineData(null, null, "a0")]
    [InlineData("a0", null, "a1")]
    [InlineData("a1", null, "a2")]
    [InlineData("az", null, "b00")]
    [InlineData("b0z", null, "b10")]
    [InlineData(null, "a0", "Zz")]
    [InlineData(null, "a1", "a0")]
    [InlineData(null, "Zz", "Zy")]
    [InlineData("a0", "a1", "a0V")]
    [InlineData("a0", "a2", "a1")]
    [InlineData("a1", "a2", "a1V")]
    [InlineData("a0V", "a1", "a0l")]
    [InlineData("Zz", "a0", "ZzV")]
    [InlineData("a0", "a0V", "a0G")]
    public void KeyBetween_matches_the_client_library(string? a, string? b, string expected) =>
        Assert.Equal(expected, FractionalIndex.KeyBetween(a, b));

    [Fact]
    public void Appending_500_keys_stays_ordered_and_short()
    {
        var keys = new List<string>();
        string? previous = null;
        for (var i = 0; i < 500; i++)
        {
            previous = FractionalIndex.KeyAfter(previous);
            keys.Add(previous);
        }

        Assert.Equal(keys, keys.Order(StringComparer.Ordinal).ToList());
        Assert.Equal(500, keys.Distinct().Count());
        Assert.Equal(3, keys.Max(k => k.Length));
        Assert.Equal("a0", keys[0]);
        Assert.Equal("b00", keys[62]);
    }

    [Fact]
    public void Repeatedly_inserting_between_the_same_pair_keeps_strict_order()
    {
        var low = "a0";
        var high = "a1";
        for (var i = 0; i < 50; i++)
        {
            var mid = FractionalIndex.KeyBetween(low, high);
            Assert.True(string.CompareOrdinal(low, mid) < 0);
            Assert.True(string.CompareOrdinal(mid, high) < 0);
            low = mid;
        }
    }

    [Fact]
    public void KeyBetween_rejects_keys_that_are_not_ascending()
    {
        Assert.Throws<ArgumentException>(() => FractionalIndex.KeyBetween("a1", "a0"));
        Assert.Throws<ArgumentException>(() => FractionalIndex.KeyBetween("a0", "a0"));
    }

    [Theory]
    [InlineData("a0", true)]
    [InlineData("b00", true)]
    [InlineData("a0V", true)]
    [InlineData("Zz", true)]
    [InlineData("~0190a00000007000800000000000000f", false)] // the DAV seam's scheme, not an order key
    [InlineData("zz", false)] // integer part shorter than its head declares
    [InlineData("a00", false)] // trailing zero in the fraction
    [InlineData("0", false)]
    [InlineData("", false)]
    [InlineData(null, false)]
    public void IsValid_accepts_only_well_formed_keys(string? key, bool expected) =>
        Assert.Equal(expected, FractionalIndex.IsValid(key));
}
